config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  get 'archive/:year_month', to: 'blogs#archive', as: 'archive'
  get 'tag/:tag_id', to: 'blogs#tag', as: 'tag', constraints: { tag_id: /.+/ }
  
  get 'archives', :to => 'archives#index', :as => 'archives'
  get 'tags', :to => 'tags#index', :as => 'tags'
  get 'about', :to => 'about#index', :as => 'about'
  
  devise_for :admins
  get 'admin', :to => 'admin#index'
  get 'admins', :to => 'admin#index'
  
  namespace :admin do
    get 'search', to: 'search#index'
    resources :blogs
    resources :tags, constraints: { id: /[^\/]+/ }
    resources :tags, only: [], constraints: { id: /[^\/]+/ } do
      resources :blogs, only: [:index]
    end
    resources :abouts
    get 'clicks', :to => 'clicks#index'
    get 'logins', :to => 'logins#index'
  end
  
  root 'blogs#index'
end

app/models/about.rb
class About < ActiveRecord::Base
  validates_presence_of :body
  validates :body, length: { maximum: 1000 }

  default_scope { order('created_at DESC') }
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :trackable, :validatable
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :clicks, :dependent => :destroy
  
  validates :title, presence: true, length: { maximum: 200 }
  validates :permalink, presence: true, length: { maximum: 200 }, uniqueness: true
  validates :body, presence: true, length: { maximum: 100000 }
  
  default_scope { order('created_at DESC') }
  
  scope :by_tag, lambda { |tag_name| joins(:tags).where("tags.name = ?", tag_name) unless tag_name.blank? }
  
  def to_param
    permalink.to_s
  end
  
  attr_accessor :tag_list

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(tags_string)
    tags_string.split(',').each do |tag|
      tag = tag.strip
      self.tags << ::Tag.where(name: tag).first_or_create unless self.tags.collect(&:name).include?(tag)
    end
    self.tags
  end
end

app/models/click.rb
class Click < ActiveRecord::Base
  belongs_to :blog

  default_scope { order('created_at DESC') }
end

app/models/login.rb
class Login < ActiveRecord::Base
  default_scope { order('created_at DESC') }
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, :dependent => :destroy
  has_many :blogs, through: :taggings
  validates :name, presence: true
  
  default_scope { order('name') }
  
  def to_param
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :blog
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @about = About.first
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin/application'
  
  def index
    @blog_count = Blog.count
    @tag_count = Tag.count
    @click_count = Click.count
    @login_count = Login.count
    @blogs = Blog.limit(10)
    
    @login = Login.where("created_at >= ? and ip = ?", Time.zone.now.beginning_of_day, request.remote_ip)
    if !@login.present?
      Login.create!({ ip: request.remote_ip })
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  include BlogsHelper
  
  def index
    @year_month_blog_count = year_month_blog_count('all')
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  include BlogsHelper
  before_action :set_about_and_archive_and_tag

  def index
  end

  def show
    @blog ||= Blog.find_by(permalink: params[:id])

    @click = Click.where("created_at >= ? and blog_id = ? and ip = ?", Time.zone.now.beginning_of_day, @blog.id, request.remote_ip)
    if !@click.present?
      Click.create!({ blog_id: @blog.id, ip: request.remote_ip})
    end
  end

  def archive
    if !params[:year_month].nil?
      @year_month_blog_count = year_month_blog_count(params[:year_month])
    end
  end

  def tag
    if !params[:tag_id].nil?
      @blogs = Blog.by_tag(params[:tag_id]).paginate(:page => params[:page])
    end
  end

  private

  def set_about_and_archive_and_tag
    @about = About.first
    @tags = Tag.all
    @blogs = Blog.paginate(:page => params[:page], :per_page => 10)
    blog_created_at = Blog.pluck(:created_at)

    @archives = Hash.new{|h, key| h[key] = []}
    blog_created_at.each do |c|
      @archives[c.strftime('%Y-%m')] << 1
    end
    @archives = Hash[@archives.map { |k, v| [k, v.reduce(:+)]}]
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      case language.to_s
      when 'rb'
        lang = 'ruby'
      when 'yml'
        lang = 'yaml'
      when ''
        lang = 'md'
      else
        lang = language
      end
      CodeRay.scan(code, lang).div
    end
  end

  def markdown(text)
    html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
    options = {
      autolink: true,
      space_after_headers: true,
      fenced_code_blocks: true,
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text).html_safe
  end
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def blog_permalink(id)
    Blog.find_by(id: id).permalink
  end
  
  def blog_entity(id)
    Blog.find_by(id: id)
  end
  
  def year_month_blogs(year_month)
    if year_month == 'all'
      Blog.all
    else
      case ActiveRecord::Base.connection.adapter_name
      when 'SQLite'
        Blog.where("created_at like ?", year_month + "%")
      when 'MySQL'
        Blog.where("created_at like ?", year_month + "%")
      when 'PostgreSQL'
        year_month_arr = year_month.split('-')
        Blog.where("date_part('year', created_at) = ? and date_part('month', created_at) = ?", year_month_arr[0], year_month_arr[1])
      else
        Blog.all
      end
    end
  end
  
  def year_month_blog_count(year_month)
    created_at = year_month_blogs(year_month).order("created_at DESC").pluck(:created_at)
    year_month_blog_count = Hash.new{ |h, key| h[key] = [] }
    created_at.each do |c|
      year_month_blog_count[c.strftime('%Y-%m')] << 1
    end
    year_month_blog_count = Hash[year_month_blog_count.map{ |k, v| [k, v.reduce(:+)] }]
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def tag_name(tag_id)
    Tag.find_by_id(tag_id).name
  end
  
  def random_color
    %w(default primary success info warning danger).sample
  end
end

app/views/admin/_blogs.html.erb
<table class="table table-bordered table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Title</th>
      <th>Permalink</th>
      <th>Body</th>
      <th>Tags</th>
      <th>Created At</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= highlight blog.title, params[:q], :highlighter => '<span style="background-color:yellow;"><a href="search?q=\1">\1</a></span>' %></td>
        <td><%= blog.permalink %></td>
        <td><%= highlight truncate(blog.body, length: 50), params[:q], :highlighter => '<span style="background-color:yellow;"><a href="search?q=\1">\1</a></span>' %></td>
        <td>
          <% blog.tags.each do |tag| %>
            <%= link_to "/admin/tags/#{tag.name}/blogs" do %>
              <span class="label label-<%= random_color %>"><%= tag.name %></span>
            <% end %>
          <% end %>
        </td>
        <td><%=l blog.created_at %></td>
        <td>
          <%= link_to admin_blog_path(blog), :class => "btn btn-info" do %>
            Show
          <% end %>
          <%= link_to edit_admin_blog_path(blog), :class => "btn btn-success" do %>
            Edit
          <% end %>
          <%= link_to admin_blog_path(blog), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" do %>
            Delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/_stats.html.erb
<div class="row placeholders">
  <div class="col-xs-6 col-sm-3 placeholder">
    <a href="<%= admin_blogs_path %>">
      <img data-src="holder.js/200x200/auto/sky/text:<%= @blog_count %>" class="img-responsive" alt="Generic placeholder thumbnail">
    </a>
    <h4>Blog</h4>
    <span class="text-muted">Total count</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <a href="<%= admin_tags_path %>">
      <img data-src="holder.js/200x200/auto/vine/text:<%= @tag_count %>" class="img-responsive" alt="Generic placeholder thumbnail">
    </a>
    <h4>Tag</h4>
    <span class="text-muted">Total count</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <a href="<%= admin_clicks_path %>">
      <img data-src="holder.js/200x200/auto/sky/text:<%= @click_count %>" class="img-responsive" alt="Generic placeholder thumbnail">
    </a>
    <h4>Click</h4>
    <span class="text-muted">Total count</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <a href="<%= admin_logins_path %>">
      <img data-src="holder.js/200x200/auto/vine/text:<%= @login_count %>" class="img-responsive" alt="Generic placeholder thumbnail">
    </a>
    <h4>Login</h4>
    <span class="text-muted">Total count</span>
  </div>
</div>

app/views/admin/index.html.erb
<h1 class="page-header">Dashboard</h1>

<%= render 'stats' %>

<h2 class="sub-header">Blog</h2>
<div class="table-responsive">
  <%= render 'blogs' %>
</div>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/admin"><%= Settings.site_name %></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/admin">Dashboard</a></li>
        <li><a href="/" target="_blank">Website</a></li>
        <li>
          <%= link_to destroy_admin_session_path, :method=>'delete' do %>
            Logout
          <% end %>
        </li>
      </ul>
      <form class="navbar-form navbar-right" action="<%= admin_search_path %>">
        <input type="text" name="q" class="form-control" placeholder="Search..." value="<%= params['q'] %>">
      </form>
    </div>
  </div>
</nav>

app/views/layouts/admin/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li<%= ' class=active' if params[:controller] == 'admin' %>><a href="/admin">Overview <span class="sr-only">(current)</span></a></li>
    <li<%= ' class=active' if params[:controller] == 'admin/blogs' or params[:controller] == 'admin/search' %>><a href="<%= admin_blogs_path %>">Blogs</a></li>
    <li<%= ' class=active' if params[:controller] == 'admin/tags' %>><a href="<%= admin_tags_path %>">Tags</a></li>
    <li<%= ' class=active' if params[:controller] == 'admin/abouts' %>><a href="<%= admin_abouts_path %>">Abouts</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li<%= ' class=active' if params[:controller] == 'admin/clicks' %>><a href="<%= admin_clicks_path %>">Clicks</a></li>
    <li<%= ' class=active' if params[:controller] == 'admin/logins' %>><a href="<%= admin_logins_path %>">Logins</a></li>
  </ul>
</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Settings.site_name %> | Dashboard</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="../css/font-awesome.css" rel="stylesheet" />
    <link href="../css/dashboard.css" rel="stylesheet" />
    <script src="../js/pace.min.js"></script>
    <link href="../css/pace.css" rel="stylesheet" />
    <script src="../js/docs.min.js"></script>
    <link rel="shortcut icon" href="favicon.ico">
  </head>
  <body>
    <%= render 'layouts/admin/header' %>
    <div class="container-fluid">
      <div class="row">
        <%= render 'layouts/admin/sidebar' %>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'layouts/scroll_top' %>
  </body>
</html>