config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  get 'archive/:year_month', to: 'blogs#archive', as: 'archive'
  get 'tag/:tag_id', to: 'blogs#tag', as: 'tag', constraints: { tag_id: /.+/ }
  
  get 'archives', :to => 'archives#index', :as => 'archives'
  get 'tags', :to => 'tags#index', :as => 'tags'
  get 'about', :to => 'about#index', :as => 'about'
  
  devise_for :admins
  get 'admin', :to => 'admin#index'
  get 'admins', :to => 'admin#index'
  
  namespace :admin do
    get 'search', to: 'search#index'
    resources :blogs
    resources :tags, constraints: { id: /[^\/]+/ }
    resources :tags, only: [], constraints: { id: /[^\/]+/ } do
      resources :blogs, only: [:index]
    end
    resources :abouts
    get 'clicks', :to => 'clicks#index'
    get 'logins', :to => 'logins#index'
  end
  
  root 'blogs#index'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, :dependent => :destroy
  has_many :blogs, through: :taggings
  validates :name, presence: true
  
  default_scope { order('name') }
  
  def to_param
    name
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin/application'
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.paginate(:page => params[:page])
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to admin_tags_url, notice: 'Successfully created.' }
        format.json { render action: 'show', status: :created, location: @tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end 
    end 
  end 

  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to admin_tags_url, notice: 'Successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end 
    end 
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to admin_tags_url, notice: 'Successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_tag
      @tag ||= Tag.find_by(name: params[:id])
    end 

    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
  def tag_name(tag_id)
    Tag.find_by_id(tag_id).name
  end
  
  def random_color
    %w(default primary success info warning danger).sample
  end
end

app/views/admin/tags/_form.html.erb
<%= f.alert_message "Please fix the errors below." %>

<%= f.text_field :name %>

<%= f.primary "Submit" %>
<%= link_to "Cancel", admin_tags_path, :class => 'btn btn-default' %>

app/views/admin/tags/edit.html.erb
<h1 class="page-header">Edit Tag</h1>

<%= bootstrap_form_for @tag, :url => { :action => "update" } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/admin/tags/index.html.erb
<h1 class="page-header">Tags</h1>

<table class="table table-bordered table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created At</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%=l tag.created_at %></td>
        <td>
          <%= link_to admin_tag_path(tag), :class => "btn btn-info" do %>
            Show
          <% end %>
          <%= link_to edit_admin_tag_path(tag), :class => "btn btn-success" do %>
            Edit
          <% end %>
          <%= link_to admin_tag_path(tag), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" do %>
            Delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @tags, renderer: BootstrapPagination::Rails %>
<div style="clear:both;"></div>

<%#= link_to "New", new_admin_tag_path, :class => 'btn btn-primary' %>

app/views/admin/tags/new.html.erb
<h1 class="page-header">New Tag</h1>

<%= bootstrap_form_for @tag, :url => { :action => "create" } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/admin/tags/show.html.erb
<h1 class="page-header">Show Tag</h1>

<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @tag.try(:name) %></dd>
</dl>

<%= link_to "Back", admin_tags_path, :class => 'btn btn-default'  %>
<%= link_to "Edit", edit_admin_tag_path(@tag), :class => 'btn btn-default' %>
<%= link_to "Delete", admin_tag_path(@tag),
              :method => 'delete',
              :data => { :confirm => 'Are you sure?' },
              :class => 'btn btn-danger' %>