config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  get 'archive/:year_month', to: 'blogs#archive', as: 'archive'
  get 'tag/:tag_id', to: 'blogs#tag', as: 'tag', constraints: { tag_id: /.+/ }
  
  get 'archives', :to => 'archives#index', :as => 'archives'
  get 'tags', :to => 'tags#index', :as => 'tags'
  get 'about', :to => 'about#index', :as => 'about'
  
  devise_for :admins
  get 'admin', :to => 'admin#index'
  get 'admins', :to => 'admin#index'
  
  namespace :admin do
    get 'search', to: 'search#index'
    resources :blogs
    resources :tags, constraints: { id: /[^\/]+/ }
    resources :tags, only: [], constraints: { id: /[^\/]+/ } do
      resources :blogs, only: [:index]
    end
    resources :abouts
    get 'clicks', :to => 'clicks#index'
    get 'logins', :to => 'logins#index'
  end
  
  root 'blogs#index'
end

app/models/about.rb
class About < ActiveRecord::Base
  validates_presence_of :body
  validates :body, length: { maximum: 1000 }

  default_scope { order('created_at DESC') }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @about = About.first
  end
end

app/controllers/admin/abouts_controller.rb
class Admin::AboutsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin/application'
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  def index
    @abouts = About.paginate(:page => params[:page])
  end

  def show
  end

  def new
    @about = About.new
  end

  def edit
  end

  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to admin_abouts_url, notice: 'Successfully created.' }
        format.json { render action: 'show', status: :created, location: @about }
      else
        format.html { render action: 'new' }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to admin_abouts_url, notice: 'Successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to admin_abouts_url, notice: 'Successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_about
      @about ||= About.find(params[:id])
    end

    def about_params
      params.require(:about).permit(:body)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/abouts_helper.rb
module Admin::AboutsHelper
end

app/views/admin/abouts/_form.html.erb
<%= f.alert_message "Please fix the errors below." %>

<%= f.text_area :body %>
<%= f.primary "Submit" %>

<%= link_to "Cancel", admin_abouts_path, :class => 'btn btn-default' %>

app/views/admin/abouts/edit.html.erb
<h1 class="page-header">Edit About</h1>

<%= bootstrap_form_for @about, :url => { :action => "update" } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/admin/abouts/index.html.erb
<h1 class="page-header">Abouts</h1>

<table class="table table-bordered table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Body</th>
      <th>Created At</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @abouts.each do |about| %>
      <tr>
        <td><%= truncate(about.body, length: 50) %></td>
        <td><%=l about.created_at %></td>
        <td>
          <%= link_to admin_about_path(about), :class => "btn btn-info" do %>
            Show
          <% end %>
          <%= link_to edit_admin_about_path(about), :class => "btn btn-success" do %>
            Edit
          <% end %>
          <%= link_to admin_about_path(about), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" do %>
            Delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @abouts, renderer: BootstrapPagination::Rails %>
<div style="clear:both;"></div>

<%= link_to "New", new_admin_about_path, :class => 'btn btn-primary' %>

app/views/admin/abouts/new.html.erb
<h1 class="page-header">New About</h1>

<%= bootstrap_form_for @about, :url => { :action => "create" } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/admin/abouts/show.html.erb
<h1 class="page-header">Show About</h1>

<dl class="dl-horizontal">
  <dt><strong>Body:</strong></dt>
  <dd><%= simple_format(@about.body) %></dd>
</dl>

<%= link_to "Back", admin_abouts_path, :class => 'btn btn-default'  %>
<%= link_to "Edit", edit_admin_about_path(@about), :class => 'btn btn-default' %>
<%= link_to "Delete", admin_about_path(@about),
              :method => 'delete',
              :data => { :confirm => 'Are you sure?' },
              :class => 'btn btn-danger' %>